[pytest]
# 测试文件所在目录
testpaths = .

;# 默认命令行参数
;# 用法：--html=<路径/文件名>  --self-contained-html
;# 示例1：生成到当前目录的 my_report.html
;#        --html=my_report.html --self-contained-html
;# 示例2：生成到子目录 reports/report.html（推荐）
;#        --html=reports/report.html --self-contained-html
;# 示例3：生成到绝对路径
;#        --html=D:/reports/my_report.html --self-contained-html
;
;# 临时改成不同的文件名
;pytest --html=my_special_report.html
;
;# 临时改成不同的路径
;pytest --html=../root_report.html
;
;# 临时关闭报告生成（不生成 html）
;pytest --html=None
addopts =
    --html=reports/report.html
    --self-contained-html
    -v
    -s
;每次运行生成报告,生成在对应项目的report文件夹下面